spring.profiles.active=dev
spring.application.name=education
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create

jwt.secret=${MY_SECRET_KEY}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=${EMAIL_PORT}
spring.mail.email=${EMAIL}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB