spring.application.name=education
spring.datasource.url=jdbc:postgresql://study-postgres:5432/cadence
spring.datasource.username=postgres
spring.datasource.password=Aymane2021
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${MY_SECRET_KEY}
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true