spring.application.name=education
spring.datasource.url=jdbc:postgresql://localhost:5432/cadence
spring.datasource.username=postgres
spring.datasource.password=Aymane2021
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect